### ISSUE TITLE
missing parameter for ASC - parameters.systemUpdatesMonitoringEffect

### ISSUE THREAD

**Issue by sunstonesecure-robert** [JupiterOne/jupiterone-alert-rules#40]
https://github.com/JupiterOne/jupiterone-alert-rules/blob/e819a5c032da32132f01b3302893d394e0b1a6b5/rule-packs/azure.json#L8

I don't see it referenced here:
https://docs.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#enforcement-mode

and in the raw data returned from the query for the policy assignment I see:
find azure_policy_assignment
...
"parameters": {},
....

**Comment by mikiodehartj1** [comment]
Removing question - pending a question rewrite. The "redesign" of the azure data model has broken the question/property is no longer being pulled in due to it causing job failures.
